=== SihamYoubi/Technologie-XML-Activit-pratique-/releveBancaire.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="releve">
    <xsd:complexType>
 <xsd:sequence>
     <xsd:element name="dateReleve" type="xsd:date" maxOccurs="1"></xsd:element>
     <xsd:element name="solde" type="xsd:double" maxOccurs="1"></xsd:element>
     <xsd:element name="operations" type="typeOperations" maxOccurs="1"></xsd:element>
 </xsd:sequence>
        <xsd:attribute name="rib" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>    
</xsd:element>
    
    
    <xsd:complexType name="typeOperations">      
        <xsd:sequence>
    <xsd:element name="operation" type="typeOperation" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="dateDebut" type="xsd:date"></xsd:attribute>
        <xsd:attribute name="dateFin" type="xsd:date"></xsd:attribute>
    </xsd:complexType>
    
    <xsd:complexType name="typeOperation">
        <xsd:attribute  name="type" default="debit">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
            <xsd:enumeration value="debit"></xsd:enumeration>
            <xsd:enumeration value="credit"></xsd:enumeration>
            </xsd:restriction>
        </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="date" type="xsd:date" use="required"></xsd:attribute>
        <xsd:attribute name="montant" type="xsd:double" use="required"></xsd:attribute>
        <xsd:attribute name="description" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

</xsd:schema>

=== SihamYoubi/Technologie-XML-Activit-pratique-/releveBancaire-schemaXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<releve xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="releveBancaire.xsd" 
    rib="97998000845346">
    <dateReleve>2021-11-10</dateReleve>
    <solde>14500</solde>
    <operations>
        <operation type="credit" date="2021-01-01" montant="9000" description="Versement Espèce"/>
        <operation type="debit" date="2021-01-05" montant="120" description="Prélèvement Assurence"/>
        <operation type="debit" date="2021-01-10" montant="3400" description="Chèque Guichet"/>
        <operation type="credit" date="2021-01-25" montant="1500" description="Virement Salaire"/>
        <operation type="debit" date="2021-01-28" montant="200" description="Achat Supermarché"/>
        <operation type="debit" date="2021-01-30" montant="300" description="Paiement Facture Électricité"/>
    </operations>
    
</releve>
